{% set name = "pymbolic" %}
{% set version = "2025.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymbolic-{{ version }}.tar.gz
  sha256: 31efa99e1f2a6407d1d7128d356dd625d56d2002d23b3f104da5b9c3fb0a270b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - constantdict
    - python >={{ python_min }}
    - immutabledict
    - pytools >=2025.2
    - typing_extensions >=4.10

test:
  requires:
    - python {{ python_min }}
    - pytest
    - matchpy
    - numpy
    - pip
  imports:
    - pymbolic
  source_files:
    - test
  commands:
    - cd test && python -m pytest
    - pip check

about:
  home: http://pypi.python.org/pypi/pymbolic
  dev_url: http://github.com/inducer/pymbolic
  doc_url: https://documen.tician.de/pymbolic
  summary: A package for symbolic computation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - inducer
