{% set name = "pymbolic" %}
{% set version = "2024.2.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymbolic-{{ version }}.tar.gz
  sha256: c993d972bf71243a98e9fce2dbc7db6eb6b0fc0e7f319c5fbeea75f98ce5288a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - immutabledict
    - pytools >=2024.1.16
    - typing_extensions >=4.5

test:
  requires:
    - python {{ python_min }}
    - pytest
    - matchpy
    - numpy
    - pip
  imports:
    - pymbolic
  source_files:
    - test
  commands:
    - cd test && python -m pytest
    - pip check

about:
  home: http://pypi.python.org/pypi/pymbolic
  dev_url: http://github.com/inducer/pymbolic
  doc_url: https://documen.tician.de/pymbolic
  summary: A package for symbolic computation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - inducer
