travis:
  secure:
    BINSTAR_TOKEN: O7Zzaqbv8GupbOG81YdR2qAuFx9LQlwyRE4Q468X+bGzDYLYGzTn6xWaULNrB7P0MECizhL+QeW6Ew1+91yEnJJKfPUwOM6SuzQuDyQfPVi2jbiMD9VQIY5QDJViWuieNC7h6XPJy506iRx2VSJnfyx6hDfgdMup1MioU4aDByfqdD97QWi3C/460D6s78x02hl0wwNmqVwo4ed3YxpF0mNuAxjXv2JmLJxD7b8ec66TT0vb9bwSDI0gBR60+1jSkSyUfsaj2W3Uss+ZVc58QbLUM0D2rzA+BufSIT0LiS73GzkhPZyCmtgr0mzuWuZ0CBupzfpEFocRG8Ph24vw5gytQqXvPldTSkfvo/arduiztLzBHdbp/XtbSeGfOUY4t8r+S7zsr+Y0xY2W/p0KM+R/gvKT66xwqYDFFTNIGoGUX1R/7x+wabR09Lww1ztuP4/ldWH5JQU1YdR5myvkiX2mOrH5aOc+d2x/zPG7aPvYH68FFpYU0K2/wbeMRSohBrfV4DHBKQl0FrAgFOp9Qhde3eu1kGP85MS6GJmSrReOWsnDapq2HP2XJNNOTx5En1uMLjxUWlEn/zH1dUJPx7tlnP/9vCD0tkYjjVu7X73/78tYKn6zUGKFV/ehfKi/lvo3ylzJCM4TlRdoNuIoRT8xp2mjc8QE2D7qlcNjzcg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
